<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Menu.aspx.cs" Inherits="Project.Menu" %>
<!DOCTYPE html>
<html>
<head runat="server">
    <title>Query Menu</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin: 10px 0;
        }
        a {
            text-decoration: none;
            color: #007bff;
            font-size: 18px;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>Hotel Management System: Query Menu</h1>
    <ul>
        <li><a href="Query1.aspx">Query 1: Guests Staying More Than 2 Days</a></li>
        <li><a href="Query2.aspx">Query 2: Employees in Front Desk Department</a></li>
        <li><a href="Query3.aspx">Query 3: Hotels with More Than 150 Rooms</a></li>
        <li><a href="Query4.aspx">Query 4: Guests and Their Total Bookings</a></li>
        <li><a href="Query5.aspx">Query 5: Total Revenue Generated by Each Hotel</a></li>
        <li><a href="Query6.aspx">Query 6: Bookings with Discounts Applied</a></li>
        <li><a href="Query7.aspx">Query 7: Room Types and Their Average Costs</a></li>
        <li><a href="Query8.aspx">Query 8: Employees Working in the Same City as Their Hotel</a></li>
        <li><a href="Query9.aspx">Query 9: Total Amount Spent by Guests on Services</a></li>
        <li><a href="Query10.aspx">Query 10: Rooms Booked Multiple Times</a></li>
        <li><a href="Query11.aspx">Query 11: Most Popular Service Used by Guests</a></li>
        <li><a href="Query12.aspx">Query 12: Employees Who Never Assisted a Booking</a></li>
        <li><a href="Query13.aspx">Query 13: Guests Who Stayed at More Than One Hotel</a></li>
        <li><a href="Query14.aspx">Query 14: Hotels and Their Total Room Count</a></li>
        <li><a href="Query15.aspx">Query 15: Hotels Where Guests Used Room Service</a></li>
        <li><a href="Query16.aspx">Query 16: Bookings in Pet-Friendly Rooms</a></li>
        <li><a href="Query17.aspx">Query 17: Hotels and Their Average Star Rating</a></li>
        <li><a href="Query18.aspx">Query 18: Guests Spending Above Average</a></li>
        <li><a href="Query19.aspx">Query 19: Employees Handling the Most Bookings</a></li>
        <li><a href="Query20.aspx">Query 20: Rooms Booked by Guests Using Two or More Services</a></li>
    </ul>
</body>
</html>
