<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Query5.aspx.cs" Inherits="Project.Query5" %>
<!DOCTYPE html>
<html>
<head runat="server">
    <title>Query 5: Total Revenue by Hotel</title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>Query 5: Total Revenue Generated by Each Hotel</h2>
        <asp:Button ID="btnFetchRevenue" runat="server" Text="Fetch Total Revenue" OnClick="btnFetchRevenue_Click" />
        <asp:GridView ID="GridView5" runat="server" AutoGenerateColumns="True"></asp:GridView>
        <div style="text-align:center; margin-top:20px;">
    <a href="Menu.aspx" style="text-decoration:none; font-size:16px; background-color:#007bff; color:white; padding:10px 15px; border-radius:5px;">Back to Menu</a>
</div>

    </form>
</body>
</html>
